const BlogData = [
  {
    id: 1,
    date: "January 01, 2020",
    catgeory: "Business ",
    title: "Phòng Superior đầy đủ tiện nghi, đáp ứng mọi nhu cầu của bạn",
    cover: "/images/singlepage/blog-1.jpg",
    para: "Phòng Superior là sự lựa chọn hoàn hảo cho những ai muốn tận hưởng một kỳ nghỉ thư thái và thoải mái. Phòng được thiết kế tinh tế và sang trọng, mang đến cho bạn cảm giác ấm cúng và tiện nghi.",
    desc: "Hướng view đẹp sẽ mang đến cho bạn những trải nghiệm tuyệt vời. Tiện nghi đầy đủ và hiện đại sẽ đáp ứng mọi nhu cầu của bạn. ",
  },
  {
    id: 2,
    date: "January 15, 2021",
    catgeory: "Traveling",
    title:
      "Thoải mái tận hưởng những giây phút nghỉ ngơi trong căn phòng sang trọng",
    cover: "/images/singlepage/blog-2.jpg",
    para: "Sự lựa chọn hoàn hảo cho những ai muốn tận hưởng một kỳ nghỉ thư thái và thoải mái. Phòng được thiết kế tinh tế và sang trọng, mang đến cho bạn cảm giác ấm cúng và tiện nghi.",
    desc: "Sự lựa chọn hoàn hảo cho những ai muốn tận hưởng một kỳ nghỉ thư thái và thoải mái. Phòng được thiết kế tinh tế và sang trọng, mang đến cho bạn cảm giác ấm cúng và tiện nghi.",
  },
  {
    id: 3,
    date: "January 21, 2018",
    catgeory: "Developement",
    title:
      "Khách sạn trang bị đầy đủ tiện nghi hiện đại, mang đến sự thoải mái cho bạn",
    cover: "/images/singlepage/blog-3.jpg",
    para: "Khách sạn của chúng tôi được trang bị đầy đủ tiện nghi hiện đại, mang đến cho bạn sự thoải mái và tiện nghi nhất trong suốt thời gian lưu trú.",
    desc: "Khách sạn của chúng tôi được trang bị đầy đủ tiện nghi hiện đại, mang đến cho bạn sự thoải mái và tiện nghi nhất trong suốt thời gian lưu trú.",
  },
  {
    id: 4,
    date: "January 30, 2019",
    catgeory: " Motion Designer",
    title:
      "Phòng nghỉ dưỡng hướng biển mang đến trải nghiệm thư giãn tuyệt vời",
    cover: "/images/singlepage/blog-4.jpg",
    para: "Phòng nghỉ dưỡng hướng biển của chúng tôi mang đến cho bạn trải nghiệm thư giãn tuyệt vời. Phòng có diện tích rộng rãi, từ 25-30m2, có hướng view đẹp nhìn ra biển. Phòng được trang bị đầy đủ tiện nghi hiện đại.",
    desc: "Phòng nghỉ dưỡng hướng biển của chúng tôi mang đến cho bạn trải nghiệm thư giãn tuyệt vời. Phòng có diện tích rộng rãi, từ 25-30m2, có hướng view đẹp nhìn ra biển. Phòng được trang bị đầy đủ tiện nghi hiện đại.",
  },
  {
    id: 5,
    date: "January 10, 2022",
    catgeory: "Content Writing",
    title: "Phòng gia đình rộng rãi, thoải mái",
    cover: "/images/singlepage/blog-5.jpg",
    para: "Phòng gia đình của chúng tôi là sự lựa chọn hoàn hảo cho những gia đình có trẻ nhỏ hoặc nhóm bạn. Phòng có diện tích rộng rãi, từ 40-50m2, có thể đáp ứng nhu cầu nghỉ dưỡng của 4-6 người. Phòng được trang bị đầy đủ tiện nghi hiện đại.",
    desc: "Phòng gia đình có đầy đủ các tiện nghi cần thiết cho gia đình bạn, bao gồm giường ngủ, tủ quần áo, bàn làm việc, tivi, điều hòa, bồn tắm hoặc vòi sen, đồ vệ sinh cá nhân và wifi tốc độ cao.",
  },
  {
    id: 6,
    date: "January 18, 2021",
    catgeory: "Web Developement",
    title: "Khách sạn mang đến cho bạn những trải nghiệm nghỉ dưỡng thượng lưu",
    cover: "/images/singlepage/blog-6.jpg",
    para: "Khách sạn của chúng tôi mang đến cho bạn những trải nghiệm nghỉ dưỡng thượng lưu. Các phòng nghỉ được thiết kế sang trọng và tinh tế, trang bị đầy đủ tiện nghi hiện đại. Khách sạn còn cung cấp các dịch vụ tiện ích cao cấp.",
    desc: "Khách sạn của chúng tôi mang đến cho bạn những trải nghiệm nghỉ dưỡng thượng lưu. Các phòng nghỉ được thiết kế sang trọng và tinh tế, trang bị đầy đủ tiện nghi hiện đại. Khách sạn còn cung cấp các dịch vụ tiện ích cao cấp.",
  },
  {
    id: 6,
    date: "January 12, 2014",
    catgeory: "Business Strategy",
    title: "Phòng suite sang trọng với ban công riêng",
    cover: "/images/singlepage/blog-1.jpg",
    para: "Phòng suite sang trọng với ban công riêng là sự lựa chọn hoàn hảo cho những ai muốn tận hưởng những trải nghiệm nghỉ dưỡng đẳng cấp. Phòng có diện tích rộng rãi, từ 60-80m2, có ban công riêng nhìn ra thành phố hoặc biển. Phòng được trang bị đầy đủ tiện nghi hiện đại.",
    desc: "Phòng suite sang trọng với ban công riêng mang đến cho bạn cảm giác thư thái và thoải mái. Bạn có thể tận hưởng những giây phút nghỉ ngơi tuyệt vời bên ban công riêng, ngắm nhìn thành phố hoặc biển cả.",
  },
  {
    id: 7,
    date: "January 30, 2019",
    catgeory: " Motion Designer",
    title: "Phòng nghỉ dưỡng sang trọng, đẳng cấp",
    cover: "/images/singlepage/blog-4.jpg",
    para: "Phòng nghỉ dưỡng sang trọng, đẳng cấp là sự lựa chọn hoàn hảo cho những ai muốn tận hưởng những trải nghiệm nghỉ dưỡng thượng lưu. Phòng được thiết kế sang trọng và tinh tế, mang đến cho bạn cảm giác ấm cúng và thư thái.",
    desc: "Tại đây, bạn có thể tận hưởng những giây phút thư giãn tuyệt vời trong không gian sang trọng và đẳng cấp. Bạn có thể tận hưởng những bữa ăn ngon được chế biến bởi các đầu bếp tài hoa tại nhà hàng của khách sạn. Bạn cũng có thể tận hưởng những liệu pháp chăm sóc sức khỏe và sắc đẹp cao cấp tại spa của khách sạn.",
  },
  {
    id: 8,
    date: "January 10, 2022",
    catgeory: "Content Writing",
    title: "Phòng nghỉ dưỡng hướng biển, tận hưởng trọn vẹn thiên nhiên",
    cover: "/images/singlepage/blog-5.jpg",
    para: "Phòng nghỉ dưỡng hướng biển, tận hưởng trọn vẹn thiên nhiên là sự lựa chọn hoàn hảo cho những ai muốn tận hưởng những giây phút thư giãn tuyệt vời bên bờ biển.",
    desc: "Bạn có thể tận hưởng những giây phút thư giãn tuyệt vời bên bờ biển, ngắm nhìn những con sóng vỗ rì rào, tận hưởng hương vị của biển cả.",
  },
];

export default BlogData;
